<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260627" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\UserControlsWPF\UserControlsWPF\UserControlsWPF.csproj" />
  </ItemGroup>
</Project>